name: PyPI Publish

on:
    release:
        types:
          - published

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: PyInfoblox Deployment
        permissions:
            id-token: write

        steps:
          - name: Checkout code
            uses: actions/checkout@main

          - name: Setup Python
            uses: actions/setup-python@main
            with:
              python-version: "3.12"

          - name: Install build dependencies
            run: |
                python -m pip install --upgrade pip
                pip install build

          - name: Build package
            run: python -m build

          - name: Publish to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
                verbose: true
                repository-url: ${{ vars.REPOSITORY_URL }}
